# Generated by Django 4.0.4 on 2022-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=25)),
                ('segundo_apellido', models.CharField(max_length=25)),
                ('puesto_trabajo', models.CharField(max_length=25)),
                ('numero_cuenta', models.IntegerField(max_length=11, unique=True)),
                ('monto_pagar', models.FloatField(max_length=10)),
            ],
        ),
    ]
