# Generated by Django 4.0.4 on 2022-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='numero_cuenta',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
