# Generated by Django 4.0.4 on 2022-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_nomina_numero_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='puesto_trabajo',
            field=models.CharField(max_length=50),
        ),
    ]
